[tasks.build-aarch64]
command = "cross"
args = ["build", "--release", "--target", "aarch64-unknown-linux-gnu"]

[tasks.upload-vps]
dependencies = ["build-aarch64"]
script = '''
ssh shaybox@vps "systemctl --user stop shaysproxy"
scp target/aarch64-unknown-linux-gnu/release/shaysproxy shaybox@vps:/home/shaybox/.cargo/bin/shaysproxy
ssh shaybox@vps "systemctl --user start shaysproxy"
'''